
.. DO NOT EDIT.
.. THIS FILE WAS AUTOMATICALLY GENERATED BY SPHINX-GALLERY.
.. TO MAKE CHANGES, EDIT THE SOURCE PYTHON FILE:
.. "examples\Maxwell2D_Transient.py"
.. LINE NUMBERS ARE GIVEN BELOW.

.. only:: html

    .. note::
        :class: sphx-glr-download-link-note

        Click :ref:`here <sphx_glr_download_examples_Maxwell2D_Transient.py>`
        to download the full example code

.. rst-class:: sphx-glr-example-title

.. _sphx_glr_examples_Maxwell2D_Transient.py:


Maxwell 2D Analysis
--------------------------------------------
This tutorial shows how you can use PyAedt to create a project in
in Maxwell2D and run a simulation

.. GENERATED FROM PYTHON SOURCE LINES 8-35

.. code-block:: default


    import sys
    import os
    import pathlib
    import shutil
    import time
    import numpy as np
    import matplotlib.pyplot as plt
    import shutil
    local_path = os.path.abspath('')
    module_path = pathlib.Path(local_path)
    root_path = module_path.parent.parent
    root_path2 = root_path.parent
    sys.path.append(os.path.join(root_path))
    sys.path.append(os.path.join(root_path2))
    example_path =os.path.join(module_path.parent,"Examples","Examples_Files")
    from pyaedt import Desktop
    from pyaedt import Maxwell2d
    from pyaedt import generate_unique_name
    project_dir = os.path.join(os.environ["TEMP"], generate_unique_name("Example"))
    if not os.path.exists(project_dir): os.makedirs(project_dir)
    print(project_dir)


    if not "oDesk" in dir():
        oDesk = Desktop(specified_version="2021.1", NG=True, AlwaysNew=False)





.. rst-class:: sphx-glr-script-out

 Out:

 .. code-block:: none

    C:\Users\mcapodif\AppData\Local\Temp\Example_HFWR1I
    Info: Using Windows TaskManager to Load processes
    Info: Ansoft.ElectronicsDesktop.2021.1 Started with Process ID 23704
    Info: pyaedt v0.5.0 started
    Info: Started external COM connection with module pythonnet_v3
    Info: Python version 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
    Info: Exe path: C:\Anaconda3\python.exe




.. GENERATED FROM PYTHON SOURCE LINES 36-37

2. Insert a Maxwell design and instantiate Geometry modeler.

.. GENERATED FROM PYTHON SOURCE LINES 37-56

.. code-block:: default


    m2d=Maxwell2d(solution_type="TransientXY")
    m2d.save_project(os.path.join(project_dir,"M2d.aedt"))
    id1=m2d.modeler.primitives.create_rectangle([0,0,0],[20,10],"Rectangle1", "copper")
    m2d.modeler.duplicate_along_line(id1, [14,0,0])

    m2d.modeler.primitives.create_region([100,100,100,100,100,100])
    m2d.assign_winding(["Rectangle1", "Rectangle1_1"], name="PHA")
    m2d.assign_balloon(m2d.modeler.primitives["Region"].edges)

    setup = m2d.create_setup()
    setup.props["StopTime"] ="0.02s"
    setup.props["TimeStep"] = "0.0002s"
    setup.props["SaveFieldsType"] = "Every N Steps"
    setup.props["N Steps"] = "1"
    setup.props["Steps From"] ="0s"
    setup.props["Steps To"] = "0.002s"
    setup.update()
    m2d.post.create_rectangular_plot("InputCurrent(PHA)",primary_sweep_variable="Time", families_dict={"Time":["All"]}, plotname="Winding Plot 1")




.. rst-class:: sphx-glr-script-out

 Out:

 .. code-block:: none

    Warning: No design present - inserting a new design
    Info: Added design 'Maxwell 2D_PVX' of type Maxwell 2D
    Info: Design Loaded
    Info: Successfully loaded project materials !
    Info: Materials Loaded
    Info: Saving Project148 Project

    True



.. GENERATED FROM PYTHON SOURCE LINES 57-58

3. Solve the Model

.. GENERATED FROM PYTHON SOURCE LINES 58-61

.. code-block:: default


    m2d.analyse_nominal()





.. rst-class:: sphx-glr-script-out

 Out:

 .. code-block:: none


    True



.. GENERATED FROM PYTHON SOURCE LINES 62-63

3. Create the Output

.. GENERATED FROM PYTHON SOURCE LINES 63-76

.. code-block:: default



    import time
    start = time.time()
    cutlist = ["Global:XY"]
    face_lists = m2d.modeler.primitives.get_object_faces("Rectangle1")
    face_lists += m2d.modeler.primitives.get_object_faces("Rectangle1_1")
    timesteps=[str(i*1e-3)+"s" for i in range(21)]

    animatedGif=m2d.post.animate_fields_from_aedtplt_2("Mag_B", face_lists, "Surface", intrinsic_dict={'Time': '0s'}, variation_variable="Time",variation_list=timesteps, off_screen=True, export_gif=True)






.. image:: /examples/images/sphx_glr_Maxwell2D_Transient_001.png
    :alt: Maxwell2D Transient
    :class: sphx-glr-single-img


.. rst-class:: sphx-glr-script-out

 Out:

 .. code-block:: none

    **************************************************************
    pyaedt Error on Method create:  General or AEDT Error. Please Check again
    Arguments Provided: 

    (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024381), None)
      File "C:\GIT\repos\pyaedt\pyaedt\modules\PostProcessor.py", line 449, in create
        self.oField.CreateFieldPlot(self.surfacePlotInstruction, "Field")



    Method Docstring: 

 
    ************************************************************
    **************************************************************
    pyaedt Error on Method create:  General or AEDT Error. Please Check again
    Arguments Provided: 

    (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024381), None)
      File "C:\GIT\repos\pyaedt\pyaedt\modules\PostProcessor.py", line 449, in create
        self.oField.CreateFieldPlot(self.surfacePlotInstruction, "Field")



    Method Docstring: 

 
    ************************************************************
    **************************************************************
    pyaedt Error on Method create:  General or AEDT Error. Please Check again
    Arguments Provided: 

    (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024381), None)
      File "C:\GIT\repos\pyaedt\pyaedt\modules\PostProcessor.py", line 449, in create
        self.oField.CreateFieldPlot(self.surfacePlotInstruction, "Field")



    Method Docstring: 

 
    ************************************************************
    **************************************************************
    pyaedt Error on Method create:  General or AEDT Error. Please Check again
    Arguments Provided: 

    (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024381), None)
      File "C:\GIT\repos\pyaedt\pyaedt\modules\PostProcessor.py", line 449, in create
        self.oField.CreateFieldPlot(self.surfacePlotInstruction, "Field")



    Method Docstring: 

 
    ************************************************************
    **************************************************************
    pyaedt Error on Method create:  General or AEDT Error. Please Check again
    Arguments Provided: 

    (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024381), None)
      File "C:\GIT\repos\pyaedt\pyaedt\modules\PostProcessor.py", line 449, in create
        self.oField.CreateFieldPlot(self.surfacePlotInstruction, "Field")



    Method Docstring: 

 
    ************************************************************
    **************************************************************
    pyaedt Error on Method create:  General or AEDT Error. Please Check again
    Arguments Provided: 

    (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024381), None)
      File "C:\GIT\repos\pyaedt\pyaedt\modules\PostProcessor.py", line 449, in create
        self.oField.CreateFieldPlot(self.surfacePlotInstruction, "Field")



    Method Docstring: 

 
    ************************************************************
    **************************************************************
    pyaedt Error on Method create:  General or AEDT Error. Please Check again
    Arguments Provided: 

    (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024381), None)
      File "C:\GIT\repos\pyaedt\pyaedt\modules\PostProcessor.py", line 449, in create
        self.oField.CreateFieldPlot(self.surfacePlotInstruction, "Field")



    Method Docstring: 

 
    ************************************************************
    **************************************************************
    pyaedt Error on Method create:  General or AEDT Error. Please Check again
    Arguments Provided: 

    (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024381), None)
      File "C:\GIT\repos\pyaedt\pyaedt\modules\PostProcessor.py", line 449, in create
        self.oField.CreateFieldPlot(self.surfacePlotInstruction, "Field")



    Method Docstring: 

 
    ************************************************************
    **************************************************************
    pyaedt Error on Method create:  General or AEDT Error. Please Check again
    Arguments Provided: 

    (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024381), None)
      File "C:\GIT\repos\pyaedt\pyaedt\modules\PostProcessor.py", line 449, in create
        self.oField.CreateFieldPlot(self.surfacePlotInstruction, "Field")



    Method Docstring: 

 
    ************************************************************
    **************************************************************
    pyaedt Error on Method create:  General or AEDT Error. Please Check again
    Arguments Provided: 

    (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024381), None)
      File "C:\GIT\repos\pyaedt\pyaedt\modules\PostProcessor.py", line 449, in create
        self.oField.CreateFieldPlot(self.surfacePlotInstruction, "Field")



    Method Docstring: 

 
    ************************************************************
    **************************************************************
    pyaedt Error on Method create:  General or AEDT Error. Please Check again
    Arguments Provided: 

    (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024381), None)
      File "C:\GIT\repos\pyaedt\pyaedt\modules\PostProcessor.py", line 449, in create
        self.oField.CreateFieldPlot(self.surfacePlotInstruction, "Field")



    Method Docstring: 

 
    ************************************************************
    **************************************************************
    pyaedt Error on Method create:  General or AEDT Error. Please Check again
    Arguments Provided: 

    (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024381), None)
      File "C:\GIT\repos\pyaedt\pyaedt\modules\PostProcessor.py", line 449, in create
        self.oField.CreateFieldPlot(self.surfacePlotInstruction, "Field")



    Method Docstring: 

 
    ************************************************************
    **************************************************************
    pyaedt Error on Method create:  General or AEDT Error. Please Check again
    Arguments Provided: 

    (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024381), None)
      File "C:\GIT\repos\pyaedt\pyaedt\modules\PostProcessor.py", line 449, in create
        self.oField.CreateFieldPlot(self.surfacePlotInstruction, "Field")



    Method Docstring: 

 
    ************************************************************
    **************************************************************
    pyaedt Error on Method create:  General or AEDT Error. Please Check again
    Arguments Provided: 

    (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024381), None)
      File "C:\GIT\repos\pyaedt\pyaedt\modules\PostProcessor.py", line 449, in create
        self.oField.CreateFieldPlot(self.surfacePlotInstruction, "Field")



    Method Docstring: 

 
    ************************************************************
    **************************************************************
    pyaedt Error on Method create:  General or AEDT Error. Please Check again
    Arguments Provided: 

    (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024381), None)
      File "C:\GIT\repos\pyaedt\pyaedt\modules\PostProcessor.py", line 449, in create
        self.oField.CreateFieldPlot(self.surfacePlotInstruction, "Field")



    Method Docstring: 

 
    ************************************************************
    **************************************************************
    pyaedt Error on Method create:  General or AEDT Error. Please Check again
    Arguments Provided: 

    (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024381), None)
      File "C:\GIT\repos\pyaedt\pyaedt\modules\PostProcessor.py", line 449, in create
        self.oField.CreateFieldPlot(self.surfacePlotInstruction, "Field")



    Method Docstring: 

 
    ************************************************************
    **************************************************************
    pyaedt Error on Method create:  General or AEDT Error. Please Check again
    Arguments Provided: 

    (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024381), None)
      File "C:\GIT\repos\pyaedt\pyaedt\modules\PostProcessor.py", line 449, in create
        self.oField.CreateFieldPlot(self.surfacePlotInstruction, "Field")



    Method Docstring: 

 
    ************************************************************
    C:\Users\mcapodif\AppData\Local\Temp\Example_HFWR1I\Mag_B_H79M3O0




.. GENERATED FROM PYTHON SOURCE LINES 77-78

Save the project and close it.

.. GENERATED FROM PYTHON SOURCE LINES 78-80

.. code-block:: default


    oDesk.force_close_desktop()








.. rst-class:: sphx-glr-timing

   **Total running time of the script:** ( 0 minutes  24.753 seconds)


.. _sphx_glr_download_examples_Maxwell2D_Transient.py:


.. only :: html

 .. container:: sphx-glr-footer
    :class: sphx-glr-footer-example



  .. container:: sphx-glr-download sphx-glr-download-python

     :download:`Download Python source code: Maxwell2D_Transient.py <Maxwell2D_Transient.py>`



  .. container:: sphx-glr-download sphx-glr-download-jupyter

     :download:`Download Jupyter notebook: Maxwell2D_Transient.ipynb <Maxwell2D_Transient.ipynb>`


.. only:: html

 .. rst-class:: sphx-glr-signature

    `Gallery generated by Sphinx-Gallery <https://sphinx-gallery.github.io>`_
